# Site settings
title: 松饼社区主站
email: rolevax@outlook.com
description: >
    松饼麻雀——高还原Saki麻将模拟器
baseurl: ""
url: ""
github_username:  rolevax
header_pages:
  - feedback.md
  - login.md
  - contribute.md
  - crowd.md
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
